### ISSUE TITLE
Why are there unrendered 7tv emotes in the recent software engineering VOD?

### ISSUE THREAD

**Issue by kevintloney** [TimIsOverpowered/nymn#2]
Within the chat of the [software engineering VOD ↗](https://nymn.gg/games/1784300749) there are blank areas where emotes should be. The html within the blank unrendered areas have reference to the emotes in a capacity much like the html where emotes are rendering properly. At times neither static emotes nor animated emotes are rendering. At other times only the 7tv emote "duckass" is rendering. Twitch emotes are always rendering just fine.

[Environment](#environment)

[Reproducing the Issue](#reproducing-the-issue)

[What the Issue Looks Like](#what-the-issue-looks-like)

## Environment

I am using [google chrome ↗](https://www.google.com/chrome/) version "111.0.5563.146 (Official Build) (x86_64)". I have included the 7tv [configuration](#7tv-configuration) I was using. I have no extensions installed that have compatibility issues with 7tv.

When I say I have no incompatible extensions, I know this because I used 7tv's compatibility checker. I included a guide on [accessing the compatibility checker](#accessing-the-7tv-compatibility-checker).

### 7tv Configuration

I am on 7tv version 3.0.3. I am using 7tv [through the chrome web store ↗](https://chrome.google.com/webstore/detail/7tv/ammjkodgmmoknidbanneddgankgfejfh).

I configured my settings as follows:

1. In the platform selection menu I chose both twitch and youtube.
2. In the "Customize Your Experience" menu I hit the configure button. I chose that I am active in chat. I used the default settings it recomends for the active chatter.

3. In the "Become a Subscriber" menu I hit "maybe later"

### Accessing the 7tv compatibility checker

To access the compatibility checker, you can use two different methods. It can be found through either the [chrome extensions menu](#chrome-extensions-menu) or a [chrome extension URL](#chrome-extension-url).

#### Chrome Extensions Menu

1. Open either the large extension menu or the small puzzle piece extension menu, find the 7tv extension, and goto extension options.
2. Select the 5th diamond on the bottom of the newly opened view.

If you want a more direct option, use the [Chrome Extension URL](#chrome-extensions-menu).

#### Chrome Extension URL

Enter the URL `chrome-extension://ammjkodgmmoknidbanneddgankgfejfh/index.html#/onboarding/compatibility` into the address bar.

There are some requirements for the method to work properly. The extension 7tv must be installed. It must be used in the address bar of either google chrome or google chrome dev. The method does not work in incognito windows. If you have issues, use the [Chrome Extensions Menu](#chrome-extensions-menu).

## Reproducing the Issue

To reproduce the issue, replicate the issue [Environment](#environment) and navigate to where the issue is visible. You can see [What the Issue Looks Like](#what-the-issue-looks-like) for reference.

Go to the [software engineering VOD↗](https://nymn.gg/games/1784300749).

* To see both static and animated emotes as unrendered, navigate to either timestamp 3:12 or 2:01:54.
* To see only the emote "duckass" being rendered, navigate to timestamp 2:11:06.

## What the Issue Looks Like

[Unrendered Static and Animated Emotes](#unrendered-static-and-animated-emotes)

[Only the "duckass" Emote Being Rendered](#only-the-duckass-emote-being-rendered)

### Unrendered Static and Animated Emotes

3:12 timestamp

![timestamp is 3:12](https://i.imgur.com/kpdCklD.png)

### Only the "duckass" Emote Being Rendered

2:11:06 timestamp

![timestamp is 2:11:06](https://i.imgur.com/ZEBHEYD.png)

**Comment by kevintloney** [comment]
I looked further into it. It looks like there issues with the cors policy. Both the cdn options you have [used](https://github.com/TimIsOverpowered/nymn/commit/435e1355fdde9883b215bc7a0bea80e822807eab) still have the same issue. Frankly I don't understand how something like "frosty" the twitch app on mobile is able to access the emotes. I checked and I know they still access the urls, but know not much beyond that. I saw that [here](https://github.com/tommyxchow/frosty/blob/5562d506dfa37c48bedf73ea0882d9652ea2689d/lib/screens/channel/chat/emote_menu/recent_emotes_panel.dart#L54). I tried figuring it out on my own, and it is beyond me.

There were some emotes that crept through the system on occasion and rendered, but they had no discernible difference besides luck i suppose.

I have a [link](https://github.com/SevenTV/API/blob/b2e2ea18a7b6a32dead026d747071de46929c08b/internal/middleware/cors.middleware.go#L24) to the middleware in question that is creating the cors policy. not absolutely sure though.

error looks as follows:
`Access to image at 'https://emotes.overpowered.tv/7tv/60ae55800e35477634f878fd/2x.webp' from origin 'https://nymn.gg' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, https://nymn.gg', but only one is allowed.`

**Comment by TimIsOverpowered** [comment]
Should be fixed. Let me know if it continues.
