### ISSUE TITLE
Can't submit imgur link as a picture

### ISSUE THREAD

**Issue by SealMann** [TimIsOverpowered/nymn#4]
It tells me that the link is invalid, I have uploaded it twice to see if a different link would fix it but it didn't.
![image](https://github.com/TimIsOverpowered/nymn/assets/40395536/a04cc921-38c4-4bd6-9864-c3e8559d42ee)

**Comment by TimIsOverpowered** [comment]
Could you try again? Pushed some fixes

**Comment by SealMann** [comment]
Sorry I know it's late but it would suck if this happened for the next review as well. 
![image](https://github.com/TimIsOverpowered/nymn/assets/40395536/6d668d39-6315-4e40-b593-4e754ad4455a)

**Comment by TimIsOverpowered** [comment]
I'm not quite understanding your problem. Have you tried resubmitting yet? I have already pushed fixes

**Comment by SealMann** [comment]
I have, that was a picture I took as I wrote the message, same problem as before.

**Comment by TimIsOverpowered** [comment]
That should not be possible because the image you linked is displaying the old version of the site. Maybe clear your browser cache?

**Comment by SealMann** [comment]
Well I'm going to clear my cache and wait for the next review, thank you for your responsiveness.
